version: 2.1

jobs:
  linux-build:
    machine: # executor type
      image: ubuntu-2004:202010-01 

    parallelism: 2
    steps:
        - checkout
        - run: |
              export DEBIAN_FRONTEND="noninteractive"
              mkdir build
              apt-get -y update
              apt-get -y install sudo 
        
        - run: echo -y | ./script/installation/packages.sh all

        - run: |
              cd ./build && cmake  ../
              cd ./build && make -j2
        
        - run: |
              cd ./build && make check-clang-tidy
              cd ./build && make check-lint
              cd ./build && make check-format
              cd ./build && make test
