name: Build Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: setup environment
          run: |
            export DEBIAN_FRONTEND="noninteractive"
            mkdir build
            sudo apt-get -y update
        
        - name: installing dependecies
          run: |
            sudo su
            echo -y | ./script/installation/packages.sh all

        - name: build 
          working-directory: ./build
          run: |
            cmake  ../
            make -j2
        
        - name: check linting & formatting
          working-directory: ./build
          run: |
            make check-format
            make check-lint
            make check-clang-tidy
            
        - name: run unit-tests
          working-directory: ./build
          run: |
            make test
            